import { Metadata } from 'next'
import React from 'react'

export const metadata: Metadata = {
  title: "Karlos's Pricing",
  description: 'Generated by next app',
  keywords: ['Pricing Page', 'FHerrera', 'KarlosVillegas', 'Next14']
}

export default  function PricingPage() {
  return (
   <>
     <div className='text-7xl'>Pricing</div>
   </>
  )
}
