import { Metadata } from 'next'
import React from 'react'


export const metadata: Metadata = {
   title: "Karlos's About",
   description: 'Generated by next app',
   keywords: ['About Page', 'FernandoH', 'KarlosVillegas', 'Next14']
 };

export default  function AboutPage() {
  return (
   <>
     <div className='text-7xl'>About</div>
   </>
  )
}
